title: "Automation Learn"
description: ""
baseurl: "/automation-learn"
url: "https://leonardespi.github.io"
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
collections:
  modules:
    output: true
    permalink: /modules/:name/
exclude:
  - README.md
  - Gemfile.lock
  - node_modules
  - vendor
sass:
  style: compressed
timezone: America/Mexico_City
